### ISSUE TITLE
CSD

### ISSUE THREAD

**Issue by vassilisw** [linuxmint/warp#13]
Hello,
Why this app is Client Side Decorated (CSD)?
I thought Mint was following the classic windows style! That’s the guidelines for XApps isn’t it?
[XApps mint guidelines](https://linuxmint-developer-guide.readthedocs.io/en/latest/xapps.html)

And I quote:

> The idea behind this project is to replace applications which no longer integrate properly outside of a particular environment (this is the case for a growing number of GNOME applications) and to give our desktop environments the same set of core applications, so that each change, each new feature being developed, each little improvement made in one of them will benefit not just one environment, but all of them.

What is going on finally? Where did the "idea" go? If you are making new apps CDS, then how and why you are "replacing" other apps with XApps?

Please note that I really love the Mint project and I am trying to HELP giving consistent and **serious** feedback.

Thanks

**Comment by mtwebster** [comment]
We weren't intending this to be a mint or xapp - it's not a 'standard' app like a text editor or image viewer, but beside that, using c-s-d in this case seemed to make more sense here when taken with the rest of the ui.  There is no need for any sort of menu bar - a single corner menu is sufficient - and it gives better overall uniformity.

This isn't the first app we've done this with - [blueberry](https://github.com/linuxmint/blueberry) for instance.

**Comment by vassilisw** [comment]
> The idea behind XApps

  has no grounds then, but ok.

Thanks for taking the time to answer.

**Comment by clefebvre** [comment]
I don't think CSD by itself stops an app from integrating properly in Cinnamon, MATE, Xfce..etc. I don't really get the point here.

**Comment by vassilisw** [comment]
Could you please mention a couple of _GNOME applications'_ characteristics, that indeed do stop apps from integrate properly in Cinnamon, MATE, etc? 
I'm trying to decode the XApps idea, mentioned above in my quote. Not by hobby, but because I' m a developer willing to contribute to linux community...

Again, thanks for your time answering this..
Vassilis

**Comment by clefebvre** [comment]
Hi Vassilis,

The quote doesn't mention CSD. In fact it's pretty vague and I think that's a good thing.

I think what's OK and not OK in terms of integration with various DEs is subjective and therefore arguable. By arguable I don't mean questionable, I mean it's really something we should be open to talk about and change with the best interest of the DEs we care for in mind.

The first question is how large we want the scope to be. I personally find it important to cover Cinnamon, MATE and Xfce. Other people might want to extend that scope to additional DEs. If they contribute to Xapps this is something we can do. In terms of compatibility, nowadays CSD is properly supported by Muffin, Marco and Xfwm, so unless we extend the scope compatibility isn't a problem here.

The second question is how different can apps be compared to native DE apps. Back in the days, GNOME apps looked like any other apps, they had titlebars, menubars, checkboxes..etc. Nowadays we're faced with new widgets.. toggle buttons, burger menus, headerbars, stack switchers, new design trends (lack of icons on buttons and/or menus, symbolic icons..etc). Some people really enjoy these changes (the GNOME dev team for instance is pushing for this), others don't want to see any of them at all (the MATE dev team is a good example of that). I'd love to hear your thoughts on this and I'll give you mine. I think we need to be pragmatic and respect the following principles:

- To make sure widgets and layouts we use are compatible with the DEs/WMs we target.
- To consider new ideas and their benefits (touch interface suitability for instance when it comes to toggle buttons, stack switchers.. dark theme support for symbolic icons)
- To accept changes once they've become mainstream (flat styles, symbolic icons for instance) but not until that happened.
- To avoid layouts/UIs which might unnecessarily create confusion in users or look different than other apps for no functional reason.

I'm also convinced there's an element of time. Trends evolve, not just in GNOME, Windows, Mac, but also on the Web, on TV, on paper, in the industry, everywhere people look. A good idea can be a good idea once it's established and accepted, but until then it's a novel idea. I don't think our goal is to invent new paradigms, new layouts, new widgets, and certainly not to promote them either. I don't think our goal is to be stuck in the past and reject anything older than GTK2 either. I think our responsibility is to be pragmatic and move at the same pace as our users, not be ahead of them and frustrate them by pushing designs they're not comfortable with yet, but not be behind them either and on the back foot still rejecting what most of them already accepted.

Going back to CSD. I've been vocal on this a few years ago. I was completely against it. I don't think I was wrong at the time, it didn't work well in many WMs and it was unpopular. It does now, and not only does it work well, it allows us to make UIs which use the same paradigms as before and look even neater. Some CSD apps look weird to me, others look really familiar.. it's not down to CSD itself, it's down to their UI design. Gnome-calc for instance uses CSD in a really cool way. It doesn't confuse users, it looks modern without coming with any cons.

We take one step at a time and we change along with other people. What looks new changes constantly, so does what looks old and what looks too new or too old.. and too different than what the rest of the DE is using.

As a sidenote XFCE itself is planning on using CSDs in most of its internal tools. Things change and that's ok. We use more and more toggle butttons and stack switchers also in Cinnamon.

**Comment by vassilisw** [comment]
Yes, **some** apps might be ok, but let me point out my point of view about some new trends:
1. You can drag n drop windows from header's buttons!! As inconvenient as it gets!
2. It does not save space, it it wasting it. Just place windows side by side and see!
3. It is often compared with OSX but this is completely wrong because OSX has and always will have menu bar.
4. lucking the menu bar, users have to seek for functionality among buttons placed left or right without any standard design.
5. Buttons are have to be left-clicked -> released -> re-click. But in the classic design you can just hold-click -> release-click on the item!!
6. The need of menubar is essential on some programs like Krita, Gimp, Inkscape, Blender, etc So we always have a mixture of CDS and non-CDS and that is bad ? design?
7. CDS will be used by apps without many "menu options", thus waste of space occurs, cos the entire header bar will be mostly empty but still there!
8. Those popup menus, so called burger menus?, that you don't see the item's parentS and if you make a mistake you have to move the mouse up and down and again and again to reach the parent! OMG...

I hope that you guys take under consideration things that make our life easier over the ones that makes it more eye-candy! And I only talk about computing here !! 

Really appreciated your time Clem...
