### ISSUE TITLE
Incompatible zeroconf service name

### ISSUE THREAD

**Issue by slowscript** [linuxmint/warp#16]
It appears that Warp's service name can be properly parsed only by itself. An example of how avahi-browse sees Warp and one properly named service:
![avahi-browse-1](https://user-images.githubusercontent.com/40033124/79071980-e1236a80-7cde-11ea-85f9-a462c308c57a.png)
I think it's mainly all the dots in the IP address that make it confused. Most services I've encountered use only one field between the dots for the service name (hostname), then two fields for service type (`._http._tcp.`) and one for domain (`local`) This incompatibility means that writing clients for Warp with other zeroconf libraries would be difficult or impossible. I've tried Android's NSD and it doesn't see it.

If you insist on having IP address in the name, I would suggest at least replacing the dots with commas or underscores. Another thing I would do is use something like `_warp._tcp` as service type (`_http._tcp` is mainly for websites). It makes the service easily identifiable and removes the need to check for "warp" in service name. The entire service name would then look something like this: `HOSTNAME__192_168_X_X._warp._tcp.local.` or just `HOSTNAME._warp._tcp.local.` without the IP. I've checked it all gets recognized correctly.
![avahi-browse-2](https://user-images.githubusercontent.com/40033124/79072207-0d8bb680-7ce0-11ea-8934-962735e33654.png)
If you agree with these changes, I could make a pull request.

**Comment by mtwebster** [comment]
Hi, I'm definitely ok with cleaning this up.

The 'embedded ip address' thing was a workaround that I never got around to trying to fix properly.  The service info sometimes had multiple ip addresses (the server's, and the client's I think), and this got it working so I could keep moving forward.  I'm not all that familiar with zeroconf, and finding implementation info (other than theory) was challenging enough that I didn't spend too much time on it.

A pull request would be welcome - we could ditch the ip address altogether if there's a way to reliably know which one to use in the service info.

I have a feeling this wouldn't be the only fix needed for allowing clients on other platforms, but it's a start.

Thanks
