### ISSUE TITLE
README doesn't tell much at all

### ISSUE THREAD

**Issue by Israel-D** [linuxmint/warp#6]
There is a serious **lack** of documentation here!

#### What is Warp?

 - Can it be used with computers that don't have it?
 - Does it work cross platform?
 - Does it use newer libraries (and that is why it needs a PPA)?
 - What versions of what libraries does it need?
 - Can they be installed via pip/pip3?
 - Where are the screenshots?

Thanks for your work, everyone knows Mint is invaluable!  This program has some amazing potential (just like Giver did! Though this seems much more robust)
I'm just getting into Python myself, and look forward to things like this becoming part of the larger FLOSS eco-system (perhaps working with @purism devices via libhandy integrations?)

**Comment by mtwebster** [comment]
Sorry just haven't got around to it, it's very much a wip and I end up breaking it every other day.  I'll see about adding a bit more info this weekend.

but to answer a few:
1 - no, all computers must have it
2 - not at the moment, but we chose a technology that *is* cross-platform for communications.
3 - it depends on what version of mint or XX distro you're on
4 - check debian/control
5 - yes - `pip3 install grpcio grpcio-tools` mainly - the rest are fairly common - see 4
6 - i'll see what I can come up with.  Again, this is a very fluid stage of development.

**Comment by mtwebster** [comment]
updated readme, I'm not going to add any more until we settle on a final name for this.
