### ISSUE TITLE
main-window.ui:19:1 Invalid object type 'XAppGtkWindow'

### ISSUE THREAD

**Issue by Justinzobel** [linuxmint/warp#8]
`(warp.py:13912): Gtk-ERROR **: 12:54:55.720: failed to add UI: /usr/share/warp/main-window.ui:19:1 Invalid object type 'XAppGtkWindow'`

I've got python3 xapp:
```
/usr/lib/python3.7/site-packages/python_xapp-1.8.1-py3.7.egg-info
/usr/lib/python3.7/site-packages/xapp/GSettingsWidgets.py
/usr/lib/python3.7/site-packages/xapp/SettingsWidgets.py
/usr/lib/python3.7/site-packages/xapp/__init__.py
/usr/lib/python3.7/site-packages/xapp/__pycache__/GSettingsWidgets.cpython-37.pyc
/usr/lib/python3.7/site-packages/xapp/__pycache__/SettingsWidgets.cpython-37.pyc
/usr/lib/python3.7/site-packages/xapp/__pycache__/__init__.cpython-37.pyc
/usr/lib/python3.7/site-packages/xapp/__pycache__/os.cpython-37.pyc
/usr/lib/python3.7/site-packages/xapp/os.py
```

**Comment by mtwebster** [comment]
That's not from python3-xapp - you need the xapp c library - I added the dependencies to the [README](https://github.com/linuxmint/warp#runtime-deps).  For this you're missing `gir1.2-xapp-1.0`.  You need to make sure you have all of those packages, though, as well as their dependencies.
